### ISSUE TITLE
Regression caused by removing support for .talismanignore

### ISSUE THREAD

**Issue by subnova** [thoughtworks/talisman#102]
Removing support for .talismanignore means that new users are now seeing errors on files which old users don't.  This means the tool no longer provides consistent behaviour for different users.  There is no migration path to .talismanrc as it does not support the behaviour of .talismanignore.

**Comment by harinee** [comment]
@subnova You are right. We hoped to tackle this with a more verbose output explaining the steps to perform.
We chose to allow users to see the output on the console itself which can be copied-pasted to .talismanrc directly, if all looks right. This will be a one-time effort, and things can move smoothly from there on.

Do you still see this to be a blocking problem?
