### ISSUE TITLE
Option to permanently ignore a file

### ISSUE THREAD

**Issue by varac** [thoughtworks/talisman#103]
If I understand correctly, at this moment talisman allows ignoring files based on a checksum, and each time a file is changed the checksum will change and the file is checked again.
I'd like to ignore a file permanently, how would I do this ?

Usecase is a backup documentation markdown file (called `backup.md`), which talisman complains about for it's filename, and which I'll never ever want talisman to check.

Is there any way with current talisman to do this ? Before, I'd  use a `.talismanignore` file which would allow me this, but how would I do this now ?

**Comment by svishwanath-tw** [comment]
I agree that talismanignore gave the option to ignore a file permanently earlier.
The reason why this functionality has been removed is that the permanently ignored file can become a place where secrets are leaked.
While we understand that it might be painful to track the checksum for every change, it provides an audit mechanism for all changes associated with an ignored file.
What do you think about this ?

**Comment by varac** [comment]
Tbh, I'm not happy with the way you you restrict users how to use talisman. I emember having a similar discussion (unfortunatly I dont know which issue this was), about wildcard ignores.
That limitation, together with this one will be probably my last usage of talisman, since it is just too restrictive and stands too much in my way. Thx anyhow for this tool, it was useful for me so far.

**Comment by sriharsha-y** [comment]
@varac 

I saw your comments on wildcards in #52 , we do have a provision to ignore entire directory or specific file through out the repo. We are trying to improve the documentation part to include such examples on wild cards. Talisman fully supports wildcards and you can even generate the checksum for wildcards using checksum calculator(https://github.com/thoughtworks/talisman#checksum-calculator) which you can copy paste in .talismanrc

Coming to ignoring files permanently, @svishwanath-tw  i think we might need to have a way to ignore a file permanently and show as a warning to the user and let him know the consequences of ignoring files permanently.
Any other thoughts ?

**Comment by harinee** [comment]
If the problem with a non-permanent ignore is usability, we could probably fix that by thinking of alternative options. One such option could be to ensure that the scan happens only on the diff of the content, and not on the complete file. Of course, this also depends on the feasibility of doing so technically. But it might be worth exploring, and so I will open a separate ticket for it.

Doing away with checksums re-introduces the danger of pushing in sensitive data in permanently ignored files, and defeats the basic purpose of having a secret detection tool.

**Comment by harinee** [comment]
Raised https://github.com/thoughtworks/talisman/issues/105 as a separate issue.
Hopefully, the issue could potentially fix the need to have a permanent ignore

**Comment by harinee** [comment]
@varac Hi, Issue #105 is now closed with the latest release: https://github.com/thoughtworks/talisman/releases/tag/v0.4.6

Could you please see if this resolves the problems you were facing too?

**Comment by harinee** [comment]
@varac could you please see if this issue can now be closed, with the latest changes in Talisman (as also mentioned in the comment above)?

**Comment by harinee** [comment]
Issue #122 has been raised to handle permanent ignore as an option for files that are scoped by technology stack, and can be assumed harmless for accidental leakage of secrets.
Please track #122 for further updates on this.

Closing this issue.
