### ISSUE TITLE
Scan only diff in content, not complete file

### ISSUE THREAD

**Issue by harinee** [thoughtworks/talisman#105]
When a file is ignored in talismanrc, and a change is made on a content which triggers talisman scan on the complete file again. The failure may be reported on the content that was not changed in the current commit.
Can we look at scanning for only the diff in content, and not the complete file again?
Something on the lines of the following maybe?
git diff --staged --name-only|xargs git diff HEAD|grep '^[+][a-z]'|cut -c 2-

(the regex might need to be tweaked, and also need to check if this will do for all the modified lines in the file. So please treat this as only an example)

**Comment by varac** [comment]
That's indeed a very good idea!

**Comment by harinee** [comment]
Closing as the latest release fixes this problem: https://github.com/thoughtworks/talisman/releases/tag/v0.4.6
