### ISSUE TITLE
report.html is not generated completely on talisman --scan

### ISSUE THREAD

**Issue by sriramsb** [thoughtworks/talisman#109]
ran talisman --scan --debug the html report was not generated completely. Ran it against talisman project and this was the output.
[talisman_reports.zip](https://github.com/thoughtworks/talisman/files/2996447/talisman_reports.zip)

**Comment by harinee** [comment]
@sriramsb We are rebuilding the HTML scan report completely. It will be enhanced with a richer look and feel.
The pull request is very close to getting fixed and merged. Hang on, while we get it done asap and write back to you.

**Comment by harinee** [comment]
@sriramsb The new HTML report was added to Talisman as a part of PR #113 
Please see if it works for you. If it looks good, please close the issue

**Comment by harinee** [comment]
Closing this since there are no further comments. Please feel free to re-open if this is not supposed to be closed, by adding further details.
