### ISSUE TITLE
is there a way to tell on the server side whether talisman is being used?

### ISSUE THREAD

**Issue by jacksingleton** [thoughtworks/talisman#11]

**Comment by harinee** [comment]
@jacksingleton what would be the purpose? Is it to track which contributors have already installed talisman and which haven't? Or is it to see if there is a possible leakage into the repo?
For the latter, we can now use the talisman scanner (from cli) on the git repo, to tell if there were any leakages

**Comment by harinee** [comment]
Closing ticket because of no further feedback. Please let us know if you would like to re-open this ticket later.
