### ISSUE TITLE
Ascii Cinema recording is archived

### ISSUE THREAD

**Issue by tkshnwesper** [thoughtworks/talisman#110]
Hey folks,

It looks like the ascii cinema recording on `gh-pages` has been archived.

<img width="751" alt="image" src="https://user-images.githubusercontent.com/7362366/55272902-16cefe80-52ea-11e9-83a6-1f7aae1919be.png">

Regards

**Comment by svishwanath-tw** [comment]
Hey @tkshnwesper ,
Thanks for pointing this out. We've managed to un-archive the recording for now.
We are following up with the owner of the recording to make the recording stick.

**Comment by harinee** [comment]
Closing this ticket as the new asciinema has been uploaded
