### ISSUE TITLE
Permanent ignore for scoped file patterns

### ISSUE THREAD

**Issue by harinee** [thoughtworks/talisman#122]
1.  Create configs in Talisman tool to maintain a list of files/file patterns, categorised by tech scope. For example, Golang scope contains pkg, lock files etc. 
2.  Add capability to .talismanrc to accept 'scope to ignore' from users. For example, they can define scope: Golang, bash, Java 
3.  Based on the scope selected, Talisman will ignore the file patterns defined in the tool's config. The rest of the files will be scanned in the same way as it does today

This way, we permanently ignore the files that are expected to contain values that would otherwise fail Talisman validations (such as, binary, hex encoded, high shannon entropy etc.) but can be considered harmless since they wouldn't be a place where users can accidentally let secrets out. 

Can you suggest an initial list of configs to start with? 
@vhasus @aaquibzama-tw @mabaritw  @rrajagop @subhrajitroy @jaydeepc and @ our other friends of Talisman

Thanks!

**Comment by svishwanath-tw** [comment]
`go.mod` and `go.sum` for golang with `GO111MODULE=on`
`Godeps/Godeps.json` and `vendor` fo  `godeps`
`Gopkg.toml`, `Gopkg.lock`, and `vendor/` for `dep`

**Comment by harinee** [comment]
@svishwanath-tw Could you please release this?

**Comment by svishwanath-tw** [comment]
@harinee : released
