### ISSUE TITLE
Talisman CLI scan should follow talismanrc

### ISSUE THREAD

**Issue by harinee** [thoughtworks/talisman#133]
Currently the CLI scan displays all the results where Talisman caught a potential secret.
There should be a way to reduce the false positives in this report, similar to the talismanrc's ignore config that we add for pre-commit/push hooks.

Notes:
- One scenario to take care of is that folks may check in their local talismanrc, and the one that the pipeline should follow can be overwritten. So talismanrc should have a signature that should be checked for scanning

**Comment by rflaperuta** [comment]
Is there a need for backwards compatibility with the current scan behavior?

**Comment by harinee** [comment]
Closing this as a duplicate of #258 . It's the same issue, so let's track there
