### ISSUE TITLE
make it clear that there is a security issue when talisman fails

### ISSUE THREAD

**Issue by jacksingleton** [thoughtworks/talisman#14]

**Comment by aaquibzama-tw** [comment]
Hi @jacksingleton . The output of talisman has been enhanced to inform the user clearly that there are security issues. 
Can you please go through the readme and see if we can close this ticket now.

**Comment by harinee** [comment]
Closing ticket because of no further feedback. Please let us know if you would like to re-open this ticket later, due to any issues in this regard.
