### ISSUE TITLE
The talisman release version 1.0.0 has wrong version tag for Darwin64

### ISSUE THREAD

**Issue by dronjax** [thoughtworks/talisman#142]
**Describe the bug**
When we try to download talisman_darwin_amd64  from release 1.0.0 and run 
`talisman_darwin_amd64 --version` it shows `talisman v0.5.0-7-g3d6907d`.

The precommit-hook will always try to update it to version 1.0.0 since it's available.

**To Reproduce**
1. Download talisman_darwin_amd64 version 1.0.0 from https://github.com/thoughtworks/talisman/releases/download/v1.0.0/talisman_darwin_amd64 .
2. Run `talisman_darwin_amd64 --version`.
3. It shows `talisman v0.5.0-7-g3d6907d`.
4. Try to run precommit hook script, it will try to update.

**Expected behavior**
It should show v1.0.0 so that it didn't try to update.
Or need to modify precommit-hook

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Version 10.14.6

**Comment by svishwanath-tw** [comment]
@dronjax Thanks for pointing this out. The problem may have been because of a CI mix-up. I'm fixing it right away.

**Comment by svishwanath-tw** [comment]
@dronjax  Please check the latest release and see if the problem is fixed.

**Comment by dronjax** [comment]
Hi @svishwanath-tw , just tested it, it works fine now, thanks.
