### ISSUE TITLE
Option to add entries to talismanrc automatically.

### ISSUE THREAD

**Issue by jpninanjohn** [thoughtworks/talisman#144]
I think an option to add entries to talismanrc automatically file when it detects violations would be very useful.

Something like how `git add -p` works. For each violation, it can interactively ask to add it to talismanrc or to ignore it.

**Comment by harinee** [comment]
@jpninanjohn is it similar to https://github.com/thoughtworks/talisman/issues/134 ?

**Comment by jpninanjohn** [comment]
No. On detecting a violation it should interactively ask if it can be ignored.. and add it to talismanrc if user approves...

**Comment by jpninanjohn** [comment]
This is done
