### ISSUE TITLE
Installing talisman on windows

### ISSUE THREAD

**Issue by Puneet1726** [thoughtworks/talisman#156]
Hi Team,

I am installing talisman on windows machine using git bash and I am getting the below error.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16239  100 16239    0     0  30072      0 --:--:-- --:--:-- --:--:-- 30128
Talisman currently only supports Windows, Linux and MacOS(darwin) systems.
If this is a problem for you, please open an issue: https://github.com/thoughtworks/talisman/issues/new

Is there anything I have missed as part of the command? Do I need to pass any arguments?

Thanks,
Puneet

**Comment by svishwanath-tw** [comment]
@Puneet1726 
Which version of windows are you using ?
Which version of gitbash are you using ?
Can you please paste the output of `uname -s` from your gitbash ?

**Comment by harinee** [comment]
Also, there are different ways to install Talisman. Could you please give us the method/command you used? @Puneet1726

**Comment by Puneet1726** [comment]
uname -s : MINGW64_NT-10.0-17763

curl --proxy xxxxx https://raw.githubusercontent.com/thoughtworks/talisman/master/global_install_scripts/install.bash > /tmp/install_talisman.bash && /bin/bash /tmp/install_talisman.bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16239  100 16239    0     0  15480      0  0:00:01  0:00:01 --:--:-- 15495
Talisman currently only supports Windows, Linux and MacOS(darwin) systems.
If this is a problem for you, please open an issue: https://github.com/thoughtworks/talisman/issues/new

**Comment by Puneet1726** [comment]
Windows 10

git --version
git version 2.23.0.windows.1

**Comment by svishwanath-tw** [comment]
@Puneet1726 I've made some changes to the installation script. Could you check if it works now ?

**Comment by Puneet1726** [comment]
Hi @svishwanath-tw 
Its working fine now.
But I am not able to see the files. I have set TALISMAN_HOME path as well.

In which path it saves the files?

**Comment by Puneet1726** [comment]
curl --proxy xxxxx https://raw.githubusercontent.com/thoughtworks/talisman/master/global_install_scripts/install.bash > /tmp/install_talisman.bash && /bin/bash /tmp/install_talisman.bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16237  100 16237    0     0  20120      0 --:--:-- --:--:-- --:--:-- 20145
Downloading dependent scripts

After this no log

**Comment by Puneet1726** [comment]
any update?

**Comment by svishwanath-tw** [comment]
> any update ?

Without more information, it is difficult to provide an "update"
I don't have access to a spare windows box to test talisman on right now, so I'll need your help with some debugging.

If you can find the time, please execute the below commands and paste the extremely verbose output a public gist and link it in your next reply:

```
export DEBUG=true 
curl --silent  https://raw.githubusercontent.com/thoughtworks/talisman/debugging/global_install_scripts/install.bash > /tmp/install_talisman_debug.bash && /bin/bash /tmp/install_talisman_debug.bash
```

**Comment by svishwanath-tw** [comment]
Hi @Puneet1726 , could you please execute the script in the previous snippet. Note that it is different from the main installation script. Also, by extremely verbose I didn't mean verbose curl output, i meant verbose script execution output. Which the new snippet produces.
Once again, for you benefit, I'm pasting the snippet below, note the changed paths in the url, it is not the same as the original talisman installation script:

```
export DEBUG=true 
curl --silent  https://raw.githubusercontent.com/thoughtworks/talisman/debugging/global_install_scripts/install.bash > /tmp/install_talisman_debug.bash && /bin/bash /tmp/install_talisman_debug.bash
```

**Comment by svishwanath-tw** [comment]
I don't have windows machine to test on.
This issue might mean that talisman needs powershell/cmd scripts for installation.

**Comment by jaydeepc** [comment]
Hey @Puneet1726,

I think this is a valid issue. I will raise a PR by EOD today and update you on this.
Hope this helps.

Thanks,
JD

**Comment by Puneet1726** [comment]
@jaydeepc : Thanks

**Comment by jaydeepc** [comment]
Hey @svishwanath-tw ,
I raised a [pull request](https://github.com/thoughtworks/talisman/pull/163) for this. Please merge if it looks okay. Below is what I added.

``` MINGW64_NT-10.0* ``` needs to be added in ```line 121``` as well in ``` global_install_scripts/install.bash ``` which will create the specific binary, as shown below:

```
                if [[ "$OS" == *"MINGW32_NT-10.0-WOW"* || "$OS" == *"MINGW64_NT-10.0"* ]]; then
			TALISMAN_BINARY_NAME="${TALISMAN_BINARY_NAME}.exe"
		fi
```
Thanks
JD

**Comment by Puneet1726** [comment]
@jaydeepc : actually  started using it on Linux instance.. I dint check on windows again.. I will check update you

**Comment by harinee** [comment]
@Puneet1726 is it fixed?

**Comment by harinee** [comment]
Closed this issue since we didn't hear further. Please feel free to reopen if the issue persists.
