### ISSUE TITLE
Not able to remove talisman from single repo

### ISSUE THREAD

**Issue by NithyaAhila** [thoughtworks/talisman#168]
**Describe the bug**
I want to remove the talisman for a single repo which has the encrypted certificates. I tried removing the pre-commit and pre-push hooks from the repo and it didnt helped and its asking to add in talismanrc file.
 Event after adding it in talismanrc it didnt helped as we used iruby to encrypt and commit.

**To Reproduce**
We will follow these steps to encrypt and decrypt the repo and commit via the ruby cli.
https://medium.com/@jonathancardoso/using-fastlane-match-with-existing-certificates-without-revoking-them-a325be69dac6

**Expected behavior**
Able to disable or remove talisman for specific repos.

**Comment by harinee** [comment]
@NithyaAhila Just to understand this better, these are the steps I understand you executed:

1. You have installed Talisman as a [global hook](https://github.com/thoughtworks/talisman/issues/165)
2. You have a repo with some encrypted files which you do not want to ignore through talismanrc, but instead prefer disabling talisman on the specific repo.
3. Under that repo, you removed .git/hooks folder manually, and tried committing/pushing to the repo again. But you still got a talisman error.

Is this right?

**Comment by NithyaAhila** [comment]
Yes Harinee.

**Comment by harinee** [comment]
i just tried this and it works fine for me
Could you test once again please? On a test repo, perhaps?
Also, which OS are you working on?

**Comment by harinee** [comment]
@NithyaAhila any updates?

**Comment by harinee** [comment]
Closing this because we didn't hear back. Please feel free to reopen if the issue still occurs
