### ISSUE TITLE
Scan for a commit id

### ISSUE THREAD

**Issue by Puneet1726** [thoughtworks/talisman#169]
Currently scanner scans the git commit history for potential secrets. 

When we add the scanner to a pipeline it will give false alerts based on the commit history.

Can we run the scan for a particular commit id?

**Comment by harinee** [comment]
@Puneet1726 why is it a false alert? The scan checks for commit history intentionally. If you have deleted secrets, but it sits in your git history somewhere, it will still be accessible.
Maybe if you describe the use-case a bit more, please?

**Comment by svishwanath-tw** [comment]
@Puneet1726 : If a file is in git commit history, it can actually be checked out at any point, which keeps your secrets vulnerable as long as the commit exists.

**Comment by harinee** [comment]
@Puneet1726 do you agree? If so, could you please close the issue?

**Comment by Puneet1726** [comment]
Please close the issue.

Thanks,
Puneet
