### ISSUE TITLE
add support for warnings?

### ISSUE THREAD

**Issue by jacksingleton** [thoughtworks/talisman#17]
for example, if PASSWORD is present in a file?

**Comment by harinee** [comment]
We have a technical support to show warnings in files.
There is also a separate detector to check if patterns containing text such as 'password' are found.

If this looks good, could you please close the issue @jacksingleton ?

**Comment by harinee** [comment]
Closing this ticket, due to no further feedback. Please do let us know if you would like to re-open this.
