### ISSUE TITLE
Add pre-commit as an option for single-repo installation

### ISSUE THREAD

**Issue by sradnev** [thoughtworks/talisman#170]
We want to enforce talisman for specific repositories, potentially as a part of setup/build scripts. Currently the `install.sh` script is **hardcoded** as a pre-push hook.

We would like to be able to easily install talisman (e.g. via an install script) for specific repositories but as a pre-commit hook. Ideally, the install.sh script should be able to take a parameter just like the global install does.

We've considered adding a custom wrapper or a custom pre-commit hook that executes the talisman binary with the correct parameters but ideally we would like to avoid having to maintain anything like that on our own.

**Comment by sradnev** [comment]
I'd be happy to add a pull request for this if people agree it is a desired feature?

**Comment by harinee** [comment]
Is it different from this?
https://github.com/thoughtworks/talisman#installation-to-a-single-project

**Comment by sradnev** [comment]
Yes, that section of the README refers to the install.sh script I meant. It has pre-push hardcoded: https://github.com/thoughtworks/talisman/blob/master/install.sh#L13

**Comment by salecharohit** [comment]
I would also like to have this feature. By default for per-project it adds a Pre-Push hook.

**Comment by dineshba** [comment]
@sradnev It looks like a desired feature. Please feel free to raise a PR
