### ISSUE TITLE
Talisman gets stuck at while displaying report on console

### ISSUE THREAD

**Issue by dcRUSTy** [thoughtworks/talisman#174]
**Describe the bug**
After analysis and during report printing phase, if it encounters a file with very large base64 string it hangs after printing "Talisman Report" on the console and remains stuck at this stage for very long time, and starts consuming some very large amount of memory which increases every second.

**To Reproduce**
1. Initialize a new empty git repository (git init)
2. Add a file with very large Base64 string (Did with 981KB base64 encoded image). Attached
3. Execute ./talisman_darwin_amd64 --githook pre-commit
4. Wait for "Talisman Report" string to appear on console.
5. Observe memory consumption in task manager (Activity Monitor) on Mac

**Expected behavior**
It should print report and checksums in a reasonable amount of time while consuming reasonable resources.

**Screenshots**
<img width="594" alt="Screenshot 2019-11-16 at 4 52 39 PM" src="https://user-images.githubusercontent.com/40319304/69002267-e936d400-0911-11ea-90b8-9cd2a2f55fe8.png">

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Version [1.0.0] of Talisman

**Additional context**
If table.AppendBulk(data) and table.Render() are replaced by fmt.Println(data) in "detection_results.go" it works. Likely to be issue with Table module

**Possible Solution**
Trim the length of base64 string or matched pattern in Report.

[test.txt](https://github.com/thoughtworks/talisman/files/3855168/test.txt)

**Comment by svishwanath-tw** [comment]
@dcRUSTy : Please check with latest code if the issue still persists

**Comment by dcRUSTy** [comment]
@svishwanath-tw it works 👍 :)
