### ISSUE TITLE
Talisman does not respect talismanrc after latest release.

### ISSUE THREAD

**Issue by jpninanjohn** [thoughtworks/talisman#177]
**Bug:**
The talismanrc has an entry for the file with the same shasum reported and yet does not ignore it.

**Steps to reproduce the behavior:**
1. Commit with a violation
2. Talisman prompts to add to talismanrc
3. Add it
4. Commit again.
5. It prompts again with same entry

Checked the talismanrc file and found the entry for the same.

**Expected behavior**
It should ignore the entry after adding to the talismanrc

**System:**
 - OS: MacOS
 - Version: talisman v1.1.0

**Comment by dineshba** [comment]
Hi @jpninanjohn I am trying to reproduce this issue. But couldn't. Below are the steps i followed

```bash
mkdir temp && cd temp/
git init
echo "password: uksPgR6dgRWAnh@5G4#U" > file.txt
git add file.txt
~/.talisman/bin/talisman_darwin_amd64 --githook pre-commit --debug -i # talisman prompted for adding file.txt to .talismanrc and i gave yes.
~/.talisman/bin/talisman_darwin_amd64 --githook pre-commit --debug -i # talisman didn't prompt as it already ignored (which is expected)
~/.talisman/bin/talisman_darwin_amd64 -v # talisman v1.1.0 I am using latest version
```
Am i following the right steps to reproduce ?

**Comment by dineshba** [comment]
@jpninanjohn Any update on this?

**Comment by jpninanjohn** [comment]
Seems to be working. Closing this issue.
