### ISSUE TITLE
ENV_FILE: unbound variable - error when upgrading talisman

### ISSUE THREAD

**Issue by prasanna** [thoughtworks/talisman#179]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by harinee** [comment]
@prasanna Could you please provide more info? Did you try to [upgrade manually](https://github.com/harinee/talisman.git)? Or was it a result of the auto-upgrade?

**Comment by harinee** [comment]
Closing due to lack of info. Please feel free to reopen with more details
