### ISSUE TITLE
ssh key files like "id_dsa_foo" are not detected

### ISSUE THREAD

**Issue by jacksingleton** [thoughtworks/talisman#18]
> I succeeded to push a DSA key named id_dsa_wgarcia in my repo, a possible fix is to replace this regexp ^.+_dsa$ by this one ^.+_dsa.*$ in https://github.com/thoughtworks/talisman/blob/master/detector/filename_detector.go#L20

**Comment by harinee** [comment]
Fixed with PR #112 
@aaquibzama-tw could you please update this ticket when the build with this PR is released?

**Comment by harinee** [comment]
The PR is merged and works as expected now.
