### ISSUE TITLE
Progress indicator for talisman scan

### ISSUE THREAD

**Issue by svishwanath-tw** [thoughtworks/talisman#180]
# Problem
Progress indicator for talisman scan

# Proposed Solution
When talisman is run in scanner mode against a repository with large number of commits
It runs for a long time without giving any feedback

# Additional context
@ravikp : Mentioned this use case when working on a codebase with a lot of commits

**Comment by harinee** [comment]
This is important. There are times that it even takes close to 15 mins to complete. Performance is another issue. But until then a progress indicator would be nice.

**Comment by tinamthomas** [comment]
Implemented and merged in this MR: https://github.com/thoughtworks/talisman/pull/268
