### ISSUE TITLE
Interactive and githook flags should be not be shown to users for talisman cli

### ISSUE THREAD

**Issue by harinee** [thoughtworks/talisman#184]
Currently as a user, I can see githook and interactive as options for talisman cli. This is useless for the user. We should remove it from the options and readme.
However, the backend functionality should remain in the code because they are used in the backend

**Comment by harinee** [comment]
Help me understand if this is a valid issue, please?

I see if I run `talisman -g pre-commit -i` then the subsequent commits are governed with an interactive mode from talisman. Was this the expected behaviour?
If so, then this issue doesn't stand valid.

Anyone please confirm my understanding. @vhasus ? @dineshba ?

**Comment by dineshba** [comment]
`talisman -g pre-commit -i` will take you to the interactive mode if we have staged changes.

I feel it is okay to show githook and interactive as options. If some users want they can run this command.
