### ISSUE TITLE
Scan should exit with proper status code on command line

### ISSUE THREAD

**Issue by harinee** [thoughtworks/talisman#186]
**Is your feature request related to a problem? Please describe.**
Talisman scan always passes on the build, and will never fail a build because the exit code is always a success even when there are issues reported

**Describe the solution you'd like**
If there are issues caught by Talisman, the exit code should fail. 
(Ideally it should be a configurable failure, where I should be able to set it based on severity levels. But that part depends on #114, so that can come later)

**Comment by tt-official** [comment]
@harinee, I tried this out and from what I can see it is returning a non-zero exit code when issues are found: 

<img width="839" alt="Screenshot 2020-03-23 at 8 46 40 PM" src="https://user-images.githubusercontent.com/42120196/77376859-cf861d00-6d47-11ea-8c67-47b99ae94c00.png">

Is there a specific scenario you saw a success error code in spite of there being reported issues?

**Comment by harinee** [comment]
Hey @tt-official Sorry for the late response.
The issue is in the talisman cli scanner, not hook. 
Please try talisman -s or talisman -w on a repo with secrets.

<img width="619" alt="Screenshot 2020-06-10 at 3 11 08 PM" src="https://user-images.githubusercontent.com/1300665/84252918-df362600-ab2c-11ea-96c8-560860f8661d.png">

**Comment by harinee** [comment]
Confirmed with @tt-official that it is spitting out an exit code as expected, and does fail the CI build.
Closing this issue as non-reproducible

<img width="1171" alt="Screenshot 2020-06-25 at 1 54 48 AM" src="https://user-images.githubusercontent.com/1300665/85624253-3b4d8e00-b687-11ea-99de-67b5d09aa174.png">
