### ISSUE TITLE
Document enabling interactive mode for hooks

### ISSUE THREAD

**Issue by arunvelsriram** [thoughtworks/talisman#190]
**Is your feature request related to a problem? Please describe.**
I couldn't find any document for enabling interactive mode for hooks. I had to look into the pre-commit hook code  and the pull request https://github.com/thoughtworks/talisman/pull/159/files#diff-203f3428655141f0a2dc2815306522b2R73

**Describe the solution you'd like**
Add steps for enabling interactive mode for hooks. I solved it by adding `export TALISMAN_INTERACTIVE=true` to `~/.bashrc`.

**Describe alternatives you've considered**
* Shall we enable interactive mode by default?
* Shall we have a flag or a prompt in the installation script to opt for interactive mode?

**Comment by harinee** [comment]
@arunvelsriram I have raised a PR to update the README, and also prompt in the installation script to opt for interactive mode.

However, I believe the README is a bug, whereas the prompt on installation is an enhancement. I will label this issue as an enhancement, to take care of both these issues.
