### ISSUE TITLE
Wildcard file ignore is not working in .talismanrc

### ISSUE THREAD

**Issue by shekhar94** [thoughtworks/talisman#191]
https://stackoverflow.com/questions/61939631/wildcard-file-ignore-is-not-working-in-talismanrc

**Comment by harinee** [comment]
@dineshba this is released, right? Can this issue be tested and closed, if found working?

**Comment by dineshba** [comment]
Added this feature in https://github.com/thoughtworks/talisman/pull/196. It will available from version v1.3.0.

Please update talisman and use this feature @shekhar94

**Comment by harinee** [comment]
Can this be closed? @shekhar94 @dineshba

**Comment by harinee** [comment]
Closing this issue for now. Please reopen if it is not working.
