### ISSUE TITLE
simplify the talisman homepage

### ISSUE THREAD

**Issue by jacksingleton** [thoughtworks/talisman#20]
Cade:

> The paragraph on the landing page https://thoughtworks.github.io/talisman/ could be reduced if you want to get people's attention. You could probably make this a single sentence (see next comment) followed by your "Learn more link". That way the viewer sees a brief statement and a quick example of it in action.
> 
> The statement "is a tool *is *to validate code changes" doesn't tell your reader what it does. What kind of validation? It's validating code changes to make sure secrets aren't accidentally checked in. (also, bold emphasis on an extra word)

**Comment by harinee** [comment]
@jacksingleton Does the readme look better now? If yes, could you please close this ticket?

**Comment by harinee** [comment]
Closing this ticket, due to no further feedback. Please do let us know if you would like to re-open this.
