### ISSUE TITLE
How to install to a single project as pre-commit?

### ISSUE THREAD

**Issue by Jinghua-Li** [thoughtworks/talisman#205]
we can install it by this command: `~/install-talisman.sh`, it can be installed by pre-push hook, But I want to install it as pre-commit hook, What should I do？Can we install  it by command `~/install-talisman.sh pre-commit`?

**Comment by harinee** [comment]
@Jinghua-Li there is an open issue #170 for installation as a pre-commit hook to a single repo.
Currently it only installs as a pre-push hook (https://github.com/thoughtworks/talisman#installation-to-a-single-project) to a single repo.
Pre-commit installation is currently supported only by global hook installation.

**Comment by Jinghua-Li** [comment]
OK，Got it, Thank you!

**Comment by harinee** [comment]
Closing this issue and we can track this with #170
