### ISSUE TITLE
regarding installation on window 10

### ISSUE THREAD

**Issue by richagupta8nov** [thoughtworks/talisman#206]
Its not a bug

I am requesting ur help, that how can i install it on window 10.
I have gone through ur article, but facing difficultly in setting up path, and also where should I place the git template folder.
request you to please help me out

**Comment by harinee** [comment]
Hi @richagupta8nov 
Please follow steps at https://github.com/thoughtworks/talisman#installation-as-a-global-hook-template
It should set up all the required path etc. Just remember to restart your terminal or _source_ your bash file, so that the changes take effect.
If you have already tried these, but faced issues, please give more details

**Comment by richagupta8nov** [comment]
Hi @harinee 

I have opened the git bash, in my repository only - so my repository is c/carepath/jassencarepath.

then I have run the command to install as git pre-commit layout. I have attached the screenshot for the same.  when it asked for the 'TALISMAN_HOME ' path, i have selected the option 1. Then it created one folder beside the source folder , under my repository. 

then it asked for the 'root directory to search for git repos' so i just typed - 'c/carepath/jassencarepath'
for which it said -'No file or directory'.


<img width="960" alt="Issue" src="https://user-images.githubusercontent.com/29193279/86781203-39b69980-c07b-11ea-89a1-c471de89d1c1.png">

**Comment by richagupta8nov** [comment]
@harinee request you to please resolve this for me, as it is really important

**Comment by harinee** [comment]
@richagupta8nov looks like the slashes are escaped, while entering the path. Unfortunately I do not have a windows setup handy. So I will need you to cooperate on the debugging part for me. 
Could you try putting double quotes around path, i.e., "C:\Carepath\janssencarepath" ?
If that doesn't work, could you try entering it as /c/Carepath/janssencarepath ?

Let me know if that works

**Comment by richagupta8nov** [comment]
Hi @harinee 

Still, the issue coming.

I know , in case it is allowed to call, then this is my mobile number -9971011772

<img width="960" alt="Issue1" src="https://user-images.githubusercontent.com/29193279/86788963-66bb7a00-c084-11ea-8b34-cf30f1a074f8.png">

**Comment by richagupta8nov** [comment]
please also confirm is the location of the 'Git Template' is correct or not.
Under 'gittemplate' folder, I have my hook file.
<img width="960" alt="GIt Template" src="https://user-images.githubusercontent.com/29193279/86789451-f103de00-c084-11ea-90fc-12f8767962bd.png">

**Comment by harinee** [comment]
@richagupta8nov please drop an email on talisman-maintainers@thoughtworks.com so that we can collaborate further from there.
I suggest you remove/hide your personal and machine information in the chats above, for your privacy.

**Comment by richagupta8nov** [comment]
@harinee 

My mail is not getting delivered.

Below is the reply

We're writing to let you know that the group you tried to contact (talisman-maintainers) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:

 * You might have spelled or formatted the group name incorrectly.
 * The owner of the group may have removed this group.
 * You may need to join the group before receiving permission to post.
 * This group may not be open to posting.

**Comment by richagupta8nov** [comment]
I have used this id only - talisman-maintainers@thoughtworks.com

**Comment by harinee** [comment]
Ok, please drop a mail to harineem@thoughtworks.com

**Comment by richagupta8nov** [comment]
have u received my mail

**Comment by harinee** [comment]
I have responded, please check

**Comment by harinee** [comment]
Closing this as resolved, as discussed with @richagupta8nov 
The issue was that the path didn't have to be entered because she needed a global hook. So a default path could be picked with an 'enter' when the path was asked for.
Also, the installation had to be invoked from home folder because the git templates were not accessible from the folder it was earlier tried from.
