### ISSUE TITLE
How do I exclude a result?

### ISSUE THREAD

**Issue by compwron** [thoughtworks/talisman#21]
This is a file that we need to check in, but it is disallowed. Right now I just temporarily remove talisman in order to check in schema changes. 

````
The following errors were detected in src/main/resources/schema.sql
	 The file name "src/main/resources/schema.sql" failed checks against the pattern \bsql|sql\b
````

**Comment by jacksingleton** [comment]
Ah, it turns out Talisman actually supports this, we just hadn't documented it!

Added a section to the readme here:

https://github.com/thoughtworks/talisman#ignoring-files

But in short... `echo src/main/resources/schema.sql >> .talismanignore`

**Comment by nipun-tw** [comment]
hey @jacksingleton what's the reasoning behind flagging a sql file as a vulnerability? shouldn't the db migration scripts checked in with the code.

**Comment by harinee** [comment]
@nipun-tw Talisman scans for potential secrets or sensitive info, not vulnerabilities.
The answer to your question is in the test file https://github.com/thoughtworks/talisman/blob/master/detector/filename_detector_test.go 
"Sql file, might be a dump and contain sensitive information"

Does that answer your question?
