### ISSUE TITLE
Talisman Report GUI when using IDE's VCS commit feature

### ISSUE THREAD

**Issue by dcRUSTy** [thoughtworks/talisman#226]
Is there a already known better method? 

I have tried this
![patch](https://user-images.githubusercontent.com/40319304/90216026-153ca280-de1b-11ea-82cc-62085495056f.PNG)
![vscode_log](https://user-images.githubusercontent.com/40319304/90216036-1a015680-de1b-11ea-8c8d-0d5dc3e77824.PNG)
![intellij_log](https://user-images.githubusercontent.com/40319304/90216053-25548200-de1b-11ea-859e-690078764f60.PNG)

**Comment by svishwanath-tw** [comment]
I want to move away from the hook script wrapper to building the functionality into talisman itself.

Having said that, this is a great first attempt.

I wonder if we can depend on a TALISMAN_PAGER program specified by the user and default to OS's native/in-built/default editor when it is not set.

How will talisman interactive mode work with this ?

**Comment by dcRUSTy** [comment]
> 
> Having said that, this is a great first attempt.

:smiley: 

> 
> I wonder if we can depend on a TALISMAN_PAGER program specified by the user and default to OS's native/in-built/default editor when it is not set.

**PAGER** sounds cool. But may complicate things even more... IDE would have already redirected stdin/stderr at the git process level.. precommit hook and then talisman will be its child. Not very sure how it will go.

> 
> How will talisman interactive mode work with this ?

Did not considered that.... Was focused mainly on getting complete log text only :sweat_smile: Never tried interactive mode.
