### ISSUE TITLE
Consider removing --silent default

### ISSUE THREAD

**Issue by kmugrage** [thoughtworks/talisman#23]
S3 is having issues today. When I ran the install script it sat on "Downloading and verifying" for a couple minutes and then exited silently. I didn't realize until I dug around that it was related to the outage.

**Comment by harinee** [comment]
@kmugrage There are a lot of changes made in the installation process and efforts to make it verbose. Please let us know if you still see any issues similar to the one reported with the latest versions.

**Comment by aaquibzama-tw** [comment]
Hi @kmugrage . Can you please take a look at the documentation and let us know if you feel the issue still exists with the latest release or if we can close this issue.

**Comment by kmugrage** [comment]
Hello @harinee and @aaquibzama-tw - I won't have a chance in the next couple weeks to try this out. Please go ahead and close this and I'll submit a new issue if I see it again.

Thanks!
