### ISSUE TITLE
This script requires 'shasum' to verify the Talisman binary.

### ISSUE THREAD

**Issue by mrinalsaurabh** [thoughtworks/talisman#24]
I am getting this error when I am trying to run ~/install-talisman.sh

**Comment by jacksingleton** [comment]
Interesting. What OS are you using? Please let me know the exact version as well as the distro if you're using Linux and shell environment if you're using Windows.

**Comment by mrinalsaurabh** [comment]
I am using CentOS 7. There was this same error message somewhere in the source code of Talisman.

**Comment by svishwanath-tw** [comment]
@mrinalsaurabh is this still an issue ?

**Comment by harinee** [comment]
Hi @mrinalsaurabh We are closing this issue as non-reproducible for now. If you are still facing any issues, please let us know if you face this again.

**Comment by mrinalsaurabh** [comment]
Thanks @harinee
