### ISSUE TITLE
regarding not able to bypass even after adding checksum in .talismanrc file

### ISSUE THREAD

**Issue by richagupta8nov** [thoughtworks/talisman#256]
@dcRUSTy

Hi 

Request you to please solve the below issue, as the talisman is being installed at 10 workstations, and but now we are facing a problem in bypassing the error.

once we commit the data, it shows the secret data in our files, and if we want to bypass that, it's not happening.

we have added the checksum code in the .taismanrc file in the project root directory, but it is still showing the error, and not let us commit.  I have created the file manually, and also tried to create the .talismanrc file with vim editor, but both ways it is not happening.

Request you to please support.

**Comment by dcRUSTy** [comment]
do share output of `type .talismanrc` if using cmd or `cat .talismanrc` if using gitbash

**Comment by svishwanath-tw** [comment]
Have you checked .talismanrc validity https://yaml-online-parser.appspot.com/ ?
Having said that we should probably build a yaml validator in talisman.

**Comment by richagupta8nov** [comment]
@svishwanath-tw 

Please check with below screen shot

![image](https://user-images.githubusercontent.com/29193279/92696321-50bd8480-f367-11ea-9caa-cd56787532fd.png)

**Comment by richagupta8nov** [comment]
> Have you checked .talismanrc validity https://yaml-online-parser.appspot.com/ ?
> Having said that we should probably build a yaml validator in talisman.

I have no idea about this

**Comment by dcRUSTy** [comment]
@svishwanath-tw i think i can reproduce this issue... with a file inside folder on windows

**Comment by dcRUSTy** [comment]
Roughest guess i could think of is path separator is `\` and not `/` in windows

**Comment by dcRUSTy** [comment]
@richagupta8nov from the screenshot file in file name remove `src/classes/` try and reply back

**Comment by svishwanath-tw** [comment]
> Have you checked .talismanrc validity https://yaml-online-parser.appspot.com/ ?
> Having said that we should probably build a yaml validator in talisman.

Thanks to @dcRUSTy for pointing out that data posted to https://yaml-online-parser.appspot.com is parsed/processed by a backend server and should not be trusted with confidential information/potential trade secrets. (USE AT YOUR OWN RISK)

**Comment by svishwanath-tw** [comment]
@dcRUSTy @richagupta8nov : https://thoughtworks.zoom.us/j/96321899310

**Comment by dcRUSTy** [comment]
@svishwanath-tw https://github.com/thoughtworks/talisman/blob/0855689c3744d15383b8ed0aeccadff90a2a9272/gitrepo/gitrepo.go#L194-L197
Guess was right
Bug was os.PathSeparator is \ on windows but git add treats path separator as /
