### ISSUE TITLE
Standalone use

### ISSUE THREAD

**Issue by Stono** [thoughtworks/talisman#26]
Hey folks, 
I want to add talisman as a stand alone scanner (not on a hook), so that I can run it as part of a tool I'm building (https://github.com/Stono/hawkeye).

Is this possible?

**Comment by svishwanath-tw** [comment]
Hi @Stono , does https://github.com/thoughtworks/talisman/pull/63 address this issue ?

**Comment by sriharsha-y** [comment]
Hi @Stono ,. Does #83 address your issue ?. If you think so,  kindly close this issue.

**Comment by harinee** [comment]
Hi @Stono We are closing this issue after testing Talisman scanner on our end.
Please use `talisman --scan` command. Look for more options by typing `talisman`
Hope you like the changes
