### ISSUE TITLE
Pre-commit hook is skipping secret texts stored as keyword in Clojure

### ISSUE THREAD

**Issue by sudhinm** [thoughtworks/talisman#263]
**Describe the bug**
Pre-commit hook is allowing me to commit some potential secret text without adding checksum in .talismanrc . We have faced this issue in a Clojure codebase. It is happening when the secret is a keyword (https://clojuredocs.org/clojure.core/keyword).

**To Reproduce**
Steps to reproduce the behaviour:
1. create a sample code which has a keyword. Eg:
`(defn credentials []
      {:username "dummy_user"
       :password "my_strong_password"})`
2. git add & git commit

**Expected behaviour**
Pre-commit hook reports the errors.

**Desktop (please complete the following information):**
 - OS: MacOS

**Comment by ravik-karn** [comment]
Adding following regex in `pattern_detector.go` fixes it. 

> {Pattern: regexp.MustCompile(`(?i)((:)(password|passphrase|secret|key|pwd|pword|pass)(.*) *[ ][^,;\n]{8,})`), Severity: severity.SeverityConfiguration["PasswordPhrasePattern"]},
