### ISSUE TITLE
Make it clearer that errors come from Talisman

### ISSUE THREAD

**Issue by kornysietsma** [thoughtworks/talisman#27]
I had half forgotten that I had installed Talisman, then I tried pushing a file containing a lot of hashes (sadly, d3.js is not Talisman's friend) and up popped a pile of warnings with no indication of what was causing them.  For a second I thought it might be something on the remote github server, until I remembered that I had Talisman installed globally.

It would be good if Talisman reported that it was the source of the warnings, possibly with a link to the github repo.

**Comment by sriharsha-y** [comment]
Hi @kornysietsma ,

Please upgrade talisman (https://github.com/thoughtworks/talisman#upgrading) and check if this is still an issue. If not kindly close this issue.

Thanks.

**Comment by harinee** [comment]
Hi @kornysietsma we are closing this issue after testing on our end. Could you please let us know if you still face issues?
