### ISSUE TITLE
Scan all code on head without going through commit history

### ISSUE THREAD

**Issue by louiedp3** [thoughtworks/talisman#271]
**Is your feature request related to a problem? Please describe.**
We want to use Talisman as part of our CI/CD pipeline. When we look over the talisman_reports/data we see that it includes issues that we have already corrected on the master branch.

**Describe the solution you'd like**
Ideally we would only scan the code on the master branch for any secrets or sensitive information. 

**Describe alternatives you've considered**
Taking a git commit SHA or set of SHAs and scanning the talisman_reports/data for that information.

**Comment by praveendvd** [comment]
WHen will this be avaliable how to build it , the command still install the cli tool without this flag

**Comment by svishwanath-tw** [comment]
@praveendvd release v1.10.0 has this feature now.
