### ISSUE TITLE
Changing default severities

### ISSUE THREAD

**Issue by steeve85** [thoughtworks/talisman#277]
Based on my experience, the `Base64Content` and `HexContent` detectors frequently identify data that is not a secret.
To reduce the number of False Positive, I would suggest [reducing the severity to Medium](https://github.com/thoughtworks/talisman/blob/master/detector/severity/severity_config.go#L28-L29). 

By doing that, users could choose to only have Talisman block commit with High severity findings (with a low chance of False Positive). What do you think? Another option that will require more effort would be to implement custom severity mapping.

Let me know what you think, and I can help to implement the option you prefer

Thanks,

**Comment by harinee** [comment]
Makes sense. But if we are downgrading severity, we might want to think of handling cases where people might be relying on 'high' severity threshold to catch Base64Content and HexContent currently.
I also like that we allow users to set their own custom threshold, through talismanrc. That should be a feature.

**Comment by steeve85** [comment]
@harinee I have implemented the feature in this PR https://github.com/thoughtworks/talisman/pull/281
