### ISSUE TITLE
package-lock.json not committable

### ISSUE THREAD

**Issue by tw-ayush** [thoughtworks/talisman#291]
We tried to install talisman for our node project. We could not find a way to make it ignore package-lock.json from secret scans.

Steps to reproduce the behaviour:
1. install pre-commit hook
2. init a node project
2. add some node dependencies. 
3. try to build the project.
4. it will create a package-lock.json file for you.
5. commit the code.

**Problem**
For an active project **package-lock.json**  tends to keep on changing with almost every commit, and the current way of ignoring such files with checksum is not feasible for such cases.

**Expected solution**
There should either be a way to mark such files to be excluded from scan completely, or some language level support to make a smart decision for which files to be excluded automatically (may be do it with a lot of noise/warnings or cautions).

**Comment by dcRUSTy** [comment]
try
https://github.com/thoughtworks/talisman#ignoring-files-by-specifying-language-scope
https://github.com/thoughtworks/talisman#ignoring-multiple-files-of-same-type-with-wildcards

**Comment by tw-ayush** [comment]
Hey thanks for the update, we somehow missed to read that section.
