### ISSUE TITLE
.talismanrc cannot handle spaces in file path

### ISSUE THREAD

**Issue by AliNL** [thoughtworks/talisman#297]
**Describe the bug**
If I have spaces in file or directory, the .talismanrc cannot config it correctly

**To Reproduce**
1. mkdir "Spaces in folder name"
2. echo "password: spacesinfoldername" > ./Spaces\ in\ folder\ name/test
3. git add .
4. git commit -m "test spaces"

**Expected behavior**
Commit should be blocked with a message for adding checksum to `.talismanrc`.
And the path should be correct.
And the suggested checksum should be changed if the password changed.

**Screenshots**
![image](https://user-images.githubusercontent.com/16043657/110608588-59ccc880-81c7-11eb-936d-dfd586912412.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7

**Comment by tinamthomas** [comment]
this is fixed with this PR: https://github.com/thoughtworks/talisman/pull/302

**Comment by tinamthomas** [comment]
@AliNL 

Fixed in this release https://github.com/thoughtworks/talisman/tree/v1.22.0
