### ISSUE TITLE
Make it simpler to install for existing Git repos

### ISSUE THREAD

**Issue by cburgmer** [thoughtworks/talisman#30]
Thanks for talisman! To make it even easier to install it across all repositories, I'd like an option to install talisman for existing Git clones (not just future ones).

Whether that is just via extending documentation, with e.g. the following snippet, or as a automatic step when running the install script outside of a Git repo, surely both would be an improvement.

```
$ find ~/my_projects -name ".git" -exec sh -c 'pushd {}/.. && ~/install-talisman.sh && popd' \;
```

**Comment by svishwanath-tw** [comment]
@cburgmer 👍  Please look at [global_install_scripts](/thoughtworks/talisman/tree/master/global_install_scripts). 
You can close this issue if you think those scripts address it.
