### ISSUE TITLE
Scrutinise for user id, signature and upstream url before commit/push

### ISSUE THREAD

**Issue by krishnakumar4a4** [thoughtworks/talisman#309]
I would like to see if talisman can make sure of the following based on some configuration
- A particular user id and email allowed for the current repository(useful when you maintain multiple user accounts)
- Signature check
- Whether upstream is changed without notice or accidentally

**Comment by svishwanath-tw** [comment]
Hey @krishnakumar4a4 , the ideas seem like a great tool for developers working with multiple projects.

I like the idea of integrating a signature check to talisman, as it is in-line with the security focus.
@harinee , @tinamthomas , @dineshba I wonder if it would move away from the main purpose of talisman being a security tool focussed on preventing secrets from being committed into a repo.

The other two ideas could be part of a new git tool focussed on multi-project contributors.
