### ISSUE TITLE
Latest Version broke talismanrc with multiple files

### ISSUE THREAD

**Issue by fpaiva-tw** [thoughtworks/talisman#314]
**Describe the bug**

Using the latest version if the commit has additions in more than 1 file, the filename pattern will only match the last pattern in the list "fileignoreconfig" of talismanrc.

**To Reproduce**
```
echo 'password: fake_password1' >> talisman_check_1.yml
echo 'password: fake_password2' >> talisman_check_2.yml
git add talisman_check_*
echo "fileignoreconfig:" > .talismanrc    
echo "- filename: talisman_check_1.yml">> .talismanrc
echo "  checksum: 2c6264526f072937cf754ed37e0a6e96346c20e6bb3274cc6074fc229161704c">> .talismanrc
echo "- filename: talisman_check_2.yml">> .talismanrc
echo "  checksum: 61c5affa3bb323e275213b1d940d1c85200c85202cd41ebef3e419b22da09cb5">> .talismanrc
git commit -m"test"
```

**Expected behavior**
The report should come clean, since both files are ignored

**Screenshots**

![Screen Shot 2021-08-10 at 19 18 09](https://user-images.githubusercontent.com/86836972/128942259-a3c58a26-d387-4c9a-94aa-a4daf2460525.png)

**Desktop**
 - OS: macOS Big Sur 11.5.1

**Comment by svishwanath-tw** [comment]
@fpaiva-tw thanks for reporting this. Am reverting the latest release.

**Comment by svishwanath-tw** [comment]
@chenrui333 : That would generally be a good idea. The default installation/update script for talisman will revert to the last released version on github. However, with *Homebrew* in the picture, things do get complicated. I wonder if something could be worked out, the only other way I can think of is to tag and older release with a newer semver, that would be confusing too.

**Comment by fpaiva-tw** [comment]
@svishwanath-tw:

In my system the suggested talismanrc is:
```
fileignoreconfig:
- filename: talisman_check_1.yml
  checksum: 2c6264526f072937cf754ed37e0a6e96346c20e6bb3274cc6074fc229161704c
- filename: talisman_check_2.yml
  checksum: 61c5affa3bb323e275213b1d940d1c85200c85202cd41ebef3e419b22da09cb5
```
I used the checksum generated by the report. You can check the issue's attached screenshot for reference.
I also used the ``` talisman --checksum=talisman_check_1.yml ``` and  ``` talisman --checksum=talisman_check_2.yml ``` and got the same results.

I am not sure why the checksum is different in my system then yours, but the bug is no concerning the checksum itself. Even if you use the checksum that your system is generating you can probably reproduce it.

**Comment by chenrui333** [comment]
> I wonder if something could be worked out, the only other way I can think of is to tag and older release with a newer semver, that would be confusing too.

Agree, a plain re-tag of an old release is kind of weird. But from a technical perspective, we should not call the already rolled out a release back to pre-release again, that is also confusing. 

It just means the release process needs to be more thoughtful and prevent the bad UX in the future. 

Either way, I think a new release would be better. :)

**Comment by chenrui333** [comment]
I actually just found a pretty similar issue that happened to graphql-java 16.0 release. It was [a problematic release](https://github.com/graphql-java/graphql-java/issues/2107), and the team create a emergency patch release 
![image](https://user-images.githubusercontent.com/1580956/129283452-2cadc6b5-4b8c-4fcf-b07e-77d203ef5245.png)

I think the situation is pretty similar like in here.
