### ISSUE TITLE
Add new filename for detection using .talismanadd file

### ISSUE THREAD

**Issue by abhsk** [thoughtworks/talisman#33]
Like .talismanignore is used for ignoring the files. Add new filename for detection using new file .talismanadd

**Comment by harinee** [comment]
@abhsk All files under a .git repo is automatically scanned, unless otherwise specified.
Do you have a particular use-case where this might be useful?

**Comment by harinee** [comment]
Closing this issue due to lack of details. Please feel free to reopen it by adding details please @abhsk
