### ISSUE TITLE
Pre-push: calculate checksum based on file content in HEAD

### ISSUE THREAD

**Issue by carhartl** [thoughtworks/talisman#342]
**Problem**

When using the `pre-push` hook, upon detecting a potential secret during push, talisman suggests to add an entry to the ignore file; I encountered that the calculated checksum for such an entry is based on the current content of the file in question, rather than what it looks like in the commit. Often times, when crafting atomic commits I may have dirty files sitting in a repository while pushing. 

When using the pre-push hook in tandem with running talisman in CI, if I was using the suggested checksum, the build might actually fail unexpectedly, because the checksum doesn't match locally and in CI.

I haven't tested that, but the problem might be similar for the pre-commit hook, where the calculated checksum would need to be based on what a file looks like in the index.

**Proposal**

I'd like to propose for talisman to suggest ignore entries with checksums calculated based on the pushed commit, or index respectively (depending on the hook in use). 

**Workaround**

When using the pre-push hook what worked for me is to stash away dirty changes and then calculate the checksum myself based on what the file looks like in the commit (== HEAD).

**Comment by LySong000** [comment]
hi, i want to ignore some files, and i following the console out put to create a new file .talismanrc to ignore it, but it looks like not working, have you encounter this issues?

**Comment by svishwanath-tw** [comment]
@carhartl : The checksum is meant to mark a point in time when a user manually confirms that a file is indeed safe and does not contain secrets. The pre-push hook only fires at the time of a git push, no way to go back in time to the offending commit, unless the user decides to do so manually.
We do output the line number at which the possible secret exists, that should help the user decide how to act on it. 

The workaround you suggest is what the pre-commit hook is meant to do, i.e. catch secrets at the time of commit.

**Comment by svishwanath-tw** [comment]
Closing this issue now.
