### ISSUE TITLE
Split into detector binary and hook setup?

### ISSUE THREAD

**Issue by spinningarrow** [thoughtworks/talisman#35]
Right now, it looks like talisman can only be used as a git hook (pre-push or pre-commit). It might be good to split out the actual detector functionality and make it more reusable. I'm thinking of things like running it on demand on a repo, a set of commits, on CI, and so on. What do you think?

**Comment by sriharsha-y** [comment]
Hi @spinningarrow 

Now we have talisman binary ( detectors) and hook script seperately. Kindly close this issue if it got resolved.

**Comment by spinningarrow** [comment]
Hi! I haven't used talisman in a while, but that sounds good. Closing the issue.
