### ISSUE TITLE
Create a Terraform scope in talisman

### ISSUE THREAD

**Issue by svishwanath-tw** [thoughtworks/talisman#353]
**Is your feature request related to a problem? Please describe.**
Terraform lock files need to be excluded from scan

**Describe the solution you'd like**
Create a terraform scope

The lock file name is `.terraform.lock.hcl`

**Comment by svishwanath-tw** [comment]
cc: @pavanthota1998 @dineshkumars0707

**Comment by svishwanath-tw** [comment]
The latest release v1.26.0, has a terraform scope (https://github.com/thoughtworks/talisman/blob/fde821f618a9269f4982f91565b551a6fa866ba0/talismanrc/scopes.go#L8) .

**Comment by pavanthota1998** [comment]
Thanks for the fix @svishwanath-tw :)
