### ISSUE TITLE
Add support for Apple M1

### ISSUE THREAD

**Issue by pexa-abruno** [thoughtworks/talisman#356]
**Apple M1 script fails - Talisman currently only supports x86 and x86_64 architectures.**

Follow instructions as per 

https://thoughtworks.github.io/talisman/docs/installation/single-repository/

**To Reproduce**

1. curl https://thoughtworks.github.io/talisman/install.sh > ~/install-talisman.sh
2. chmod +x ~/install-talisman.sh
3. mkdir repo
4. cd repo
5. ~/install-talisman.sh

Not running from inside a git repository... installing as a
git template.

If you meant to install to a specific repo, 'cd' into that
repo and run this script again.

Installing as a template will automatically add Talisman to
any new repo that you 'init' or 'clone'.

No git template directory is configured. Let's add one.
(this will override any system git templates and modify your git config file)

Git template directory: (/Users/abruno/.git-templates)

Talisman currently only supports x86 and x86_64 architectures.
/Users/abruno/install-talisman.sh: line 105: INSTALL_ORG_REPO: unbound variable

**Expected behavior**

As documented

**Comment by pexa-abruno** [comment]
Using `brew install talisman` is an alternative

e.g.
`
#!/bin/bash

brew install talisman

ln -sFf $(pwd)/scripts/githooks/* $(pwd)/.git/hooks/

rm -f .git/hooks/pre-commit
talisman -g pre-commit
`

**Comment by svishwanath-tw** [comment]
@pexa-abruno : I've fixed the install script. Could you check now if it works for you ?

**Comment by pexa-abruno** [comment]
Nope.  Just tested 

curl https://thoughtworks.github.io/talisman/install.sh > ~/install-talisman.sh

Talisman currently only supports x86 and x86_64 architectures.
/Users/abruno/install-talisman.sh: line 105: INSTALL_ORG_REPO: unbound variable

**Comment by pexa-abruno** [comment]
Using curl https://raw.githubusercontent.com/thoughtworks/talisman/a8b8b8c63181c1560c8b1a8aed8235d6d2aebf8a/install.sh > ~/install-talisman.sh it worked on M1.

PR looks good, can merge.

**Comment by pexa-abruno** [comment]
OK, this also works - so it was merged.

 https://raw.githubusercontent.com/thoughtworks/talisman/master/install.sh = GOOD

BUT 
  
  https://thoughtworks.github.io/talisman/install.sh = NOT UPDATED!
