### ISSUE TITLE
Leverage phishing website & addresses database to protect users

### ISSUE THREAD

**Issue by Tbaut** [thoughtworks/talisman#361]
**Is your feature request related to a problem? Please describe.**
When a user visits a phishing website, Talisman should redirect them, the way Polkadot.js extension does.

**Describe the solution you'd like**
There's a community driven repo https://polkadot.js.org/phishing/ with a list of phishing website and known scammer accounts. Talisman should leverage this database to inform users about phishing website and before sending any token to known phishing addresses.

**Comment by harinee** [comment]
Thanks for raising the issue.
But Talisman does not control, track, intercept or acknowledge any navigations that a user makes.
Closing the issue, as this does not align with the product vision of Talisman.

**Comment by Tbaut** [comment]
Such a disappointing answer. You do know what website is currently linked to Talisman since you keep track of what website was authorized to share the user accounts with. This goes without saying that this is a local information and it shouldn't be tracked by anything else than the extension itself. The feature I describe is supported by extensions like Metamask, Polkadot.js extension, or Subwallet, it does not compromise user privacy, and is actually built to prevent them getting scammed/phished.

**Comment by Tbaut** [comment]
Looks like I opened an issue in the wrong repo. Apologies :)
