### ISSUE TITLE
Pre-commit hook not finding talisman executable in single project hook

### ISSUE THREAD

**Issue by pee-tw** [thoughtworks/talisman#385]
**Describe the bug**
Repo level Talisman doesn't find 

**To Reproduce**
Setting pre-commit hook like the sample in the README

**Expected behavior**
It should run without problems

**Screenshots**

<img width="681" alt="Screen Shot 2565-08-11 at 10 55 58" src="https://user-images.githubusercontent.com/76930028/184082143-1eae5a22-4c4b-4edb-91c8-3aa03f6924d2.png">

**Additional context**
Please accept PR for README fix

**Comment by svishwanath-tw** [comment]
Approved and PR much appreciated!
