### ISSUE TITLE
Problem with Regex (allowed_patterns)

### ISSUE THREAD

**Issue by johnoliv** [thoughtworks/talisman#391]
I need to ignore a known hex-encoded text inside some files using an allowed_patterns regex, but I don't want to skip the whole content. 

**Example of error:**
Expected file to not to contain hex-encoded texts such as:
"d-b776a0bdace0449c81ca4284683XXXXX",

Expected file to not to contain hex-encoded texts such as:
 "d-baeb9610e69043be9d315d7e351XXXXX",

![image](https://user-images.githubusercontent.com/18710805/190692573-69d97355-4397-4d7e-91b8-c236e78f0c38.png)

The text pattern is:
Initial d- with 32 characters.

I tried to use the following regex without success:
**.talismanrc**
allowed_patterns:
- ([\w]*d-[\w]*)
- (\bd-[\w]{32})
- ([\w]*d-[\w]*)
- (d-[\w]{32})
- ([d]-[\w]*)
- (["]d-[\w]{32}["]*)

**More info:**
OS: macOS 12.5.1
Talisman v1.28.1

**Comment by jmatias** [comment]
Thanks for raising this issue, we'll look into it

**Comment by svishwanath-tw** [comment]
@johnoliv : I tried `d-[0-9a-fA-F]{32}` [regex101.com](https://regex101.com/r/Wyvbwb/1) with language set to golang. This should help your case.

**Comment by tinamthomas** [comment]
Hmm, thats odd. I tried with the regex as well, and even though the regex is valid, talisman still seems to be flagging it as an  error. I can take a look at it and see what's happening.

**Comment by johnoliv** [comment]
> Hmm, thats odd. I tried with the regex as well, and even though the regex is valid, talisman still seems to be flagging it as an error. I can take a look at it and see what's happening.

Thank you @tinamthomas. Appreciate your help.
