### ISSUE TITLE
Talisman HTML Report doesn't work

### ISSUE THREAD

**Issue by mahmud92542** [thoughtworks/talisman#398]
**Describe the bug**
After installing HTML Report, when I scan my folder by generating a folder called talisman_html_report & try to see from the browser, it actually shows sample data, not the real data. If you go to the talisman_html_report folder, you'll see under the sample folder there are some png image that actually shows on the index.html. but if you go to the data folder & open your report.json you'll see the actual scan report of your repo. sometimes HTML page shows nothing.

**To Reproduce**
1. Go to the project folder
2. Click on the talisman_html_report folder
3. Scroll down & go to the sample folder
4. you'll see some png file that actually shows you the report when you try to see your report on the browser

**Expected behavior**
How can I show the actual report on the index.html page, this the expectations?

**Screenshots**
![Screenshot 2022-10-06 at 1 38 22 PM](https://user-images.githubusercontent.com/34007876/194248647-7fc9dea8-947c-415e-b564-ea9ad2784534.png)
![Screenshot 2022-10-06 at 1 39 18 PM](https://user-images.githubusercontent.com/34007876/194248661-bc7414b2-5882-4233-9c73-26751ed053e3.png)

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [chrome]
 - Version [106.0.5249.91]

**Comment by tinamthomas** [comment]
How are you viewing the html report from the browser? You would see empty data if you're only viewing only the html file directly.

Did you try navigating to the talisman_html_report and starting a server with this command?

python -m SimpleHTTPServer

**Comment by mahmud92542** [comment]
I see!
I run the talisman --scanWithHtml in the project directory. then run the HTTP Server from the same directory. then go to the talisman_html_report from the browser. 

but now, I tried what you suggested & can see the report.

Thanks a lot! I didn't try this way. 

btw, for python3, the server will run with the below command, 
python3 -m http.server <port_number>

**Comment by tinamthomas** [comment]
Awesome! Glad that was sorted out!

**Comment by nafanz** [comment]
I don't want to create a new discussion, `-w` or `--scanWithHtml` don't work for me either.
Please help me figure out where I made a mistake.

I installed `talisman` with the command
```
bash -c "$(curl --silent https://raw.githubusercontent.com/thoughtworks/talisman/main/install.sh)"
```

Checked where it is installed `which talisman`
```
/usr/local/bin/talisman
```

Installed `talisman-html-report`
```
ls -1 /home/qa/.talisman/talisman-html-report
css
data
fonts
img
index.html
js
README.md
sample
Talisman-Infographic.png
talisman.png
```

If I run the server `python3 -m http.server 8000` in this directory everything works, I see the default report for the example. I can also place my report file there and view it

But `talisman -w` doesn't work for me
```
Looks like you are using 'talisman --scanWithHtml' for scanning.
But it appears that you have not installed Talisman Html Report
Please go through Talisman Readme and make sure you install the same from:

https://github.com/jaydeepc/talisman-html-report

OR use 'talisman --scan' if you want the JSON report alone

Failed: Unable to perform Scan

2024/12/26 13:32:41 Run Status: Failed
```

**Comment by mahmud92542** [comment]
@nafanz 

The logs suggest you already have talisman-html-report installed in your user directory (/home/qa/.talisman/talisman-html-report). However, talisman might not be configured to find it there. You can try reinstalling it globally using the following command & then check:

pip install talisman-html-report

**Comment by nafanz** [comment]
Ubuntu 24.04.1 LTS
Python 3.12.3

Received such a warning:
```
pip install talisman-html-report
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
```

Tried the unwanted option.
```
pip install talisman-html-report --break-system-packages
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement talisman-html-report (from versions: none)
ERROR: No matching distribution found for talisman-html-report
``

And recommended.
```
pipx install talisman-html-report
Fatal error from pip prevented installation. Full pip output in file:
    /home/qa/.local/state/pipx/log/cmd_2024-12-26_14.47.20_pip_errors.log

Some possibly relevant errors from pip install:
    ERROR: Could not find a version that satisfies the requirement talisman-html-report (from versions: none)
    ERROR: No matching distribution found for talisman-html-report

Error installing talisman-html-report.
```

In general, searching pypi.org does not find such a package.

**Comment by mahmud92542** [comment]
@nafanz Try with pip3, pip3 install talisman-html-report, my one worked on Mac, but I am unsure about Ubuntu 24.04.1 LTS.
