### ISSUE TITLE
How do I remove/uninstall talisman?

### ISSUE THREAD

**Issue by thadeuszlay** [thoughtworks/talisman#41]
Two questions:
1) How do I remove talisman inside my project, i.e. locally?
2) How do I remove talisman globally?

**Comment by bholagabbar** [comment]
@jacksingleton I see you're an active committer. Could you please shed some light on this issue, I'm having trouble removing talisman too

**Comment by mariusz-zawadzki** [comment]
Hi. 

I just tried that.
By default it is installed in as file "~/.git-templates/hooks/pre-push" so remove this.

If you have an existing repo that was "git init" or "git clone" when Talisman was installed got ".git/hooks" of that repo and remove pre-push. 

Worked like a charm for me.

**Comment by svishwanath-tw** [comment]
You folks should take a look at [global_install_scripts](https://github.com/thoughtworks/talisman/tree/master/global_install_scripts) and see if this is step in the right direction.

**Comment by aaquibzama-tw** [comment]
Issue has been fixed with [this commit](https://github.com/thoughtworks/talisman/commit/6e4d59b88f5937cef9b639e8af7716ea060563e7)

You will have to use the uninstall.bash to remove Talisman.
