### ISSUE TITLE
git push --set-upstream origin my-new-branch hangs

### ISSUE THREAD

**Issue by JannikArndt** [thoughtworks/talisman#42]
When I create a new branch locally and want to push it, setting the upstream fails:

```bash
$ git push --set-upstream origin my-new-branch
```

(the operation just hangs)

## Steps to reproduce

```bash
$ git checkout -b my-new-branch
$ echo "foo" > file.txt
$ git add file.txt
$ git commit -m "Test"
$ git push --set-upstream origin my-new-branch
```

## Context
System: MacOS 10.13.2
Shell: zsh 5.3
Git: 2.16.0

**Comment by harinee** [comment]
@JannikArndt I could not reproduce this. Could you please try this scenario again with the latest Talisman in place, and let us know if the issue still persists?

**Comment by JannikArndt** [comment]
Sorry, I neither have the same machine anymore, nor any of the old versions, nor talisman installed. I would just close this issue.

**Comment by electrofelix** [comment]
I've just hit a couple of hangs recently with the latest release, it appears that a call to `git ls-tree -r <commitish>` can sometimes get stuck. This on Ubuntu 18.04, bash 4.4.19(1)-release, & git 2.17.1.

{noformat}
<user>  8329  0.0  0.0  85144  7688 pts/1    S+   14:59   0:00 git ls-tree -r 955ba3c6e5d21ce0803ae21e8bbadbf5746b26a8
<user>  8331  0.0  0.0  85144  7704 pts/1    S+   14:59   0:00 git ls-tree -r 870b78899c2d68a87cf171256ed124f3e0b13b93
{noformat}

@harinee should I open a new issue or just include here?

**Comment by svishwanath-tw** [comment]
@electrofelix : does a manual invocation of 
`git ls-tree -r 955ba3c6e5d21ce0803ae21e8bbadbf5746b26a8`
or
`git ls-tree -r 870b78899c2d68a87cf171256ed124f3e0b13b93`
hang ? If yes could this be a repo specific issue ?

**Comment by Mahdiyeh** [comment]
I did with `git push origin `NameOfBranch``
