### ISSUE TITLE
Does not work for multiple commits.

### ISSUE THREAD

**Issue by mariusz-zawadzki** [thoughtworks/talisman#45]
Talisman blocked default README.md from "create-react-app" but allowed to push when I cleared README.md in second commit.

Example here:
https://github.com/mariusz-zawadzki/montessori-teacher-tools/commits/master

Steps to recreate:
1. Init a repo
2. add a file that has **content** that is not allowed.
3. git commit
4. git push (get failure)
5. Clear/fix content of said file.
6. git commit
7. git push (success, expected failure)

**Comment by Aiko-Klostermann** [comment]
Known issue.
Addressed by #16

**Comment by AikoPath** [comment]
Known issue.
Addressed by #16 bug: talisman allows push when user adds a commit to delete the added secret

**Comment by harinee** [comment]
Marking as duplicate of #16 
Let's track that issue
