### ISSUE TITLE
Add more specific options to ignore false positives than on file level.

### ISSUE THREAD

**Issue by AikoPath** [thoughtworks/talisman#47]
When I have a false positive on an environment config file I can only .talisman**ignore** the complete file.
At this point, talisman has mostly become useless for the given repository. Since the one file that has the highest probability where I accidentally have credentials stored would be that environment config file.

This has happened multiple times to me. I don't remember the exact use cases but something like google analytics tracking id or something else that looks like a secret that I need to send to my Frontend.

If I could ignore the exact string value of the false positive I could continue to get the file checked for future pushes while also push when the false positive comes up.

This is related to / another reason for #39.

**Comment by AikoPath** [comment]
Related to #39

**Comment by flosell** [comment]
Related PR about ignoring only specific detectors: #38 
Also discusses if we need a more powerful configuration format to support features like what you describe

**Comment by harinee** [comment]
@AikoPath .talismanrc allows you to ignore a state of file (using checksums). This means if your config file had a modification, and that introduces a possible sensitive information, talisman scan will execute again and report it.
Additionally, if the config file changes, but does NOT introduce anything that breaks one of Talisman's validations, Talisman would be happy with the changes and not shout out.
Hope this resolves your problem. If it does, please close the issue.
