### ISSUE TITLE
Homebrew based installation of talisman binary on MacOS

### ISSUE THREAD

**Issue by prateekbaheti** [thoughtworks/talisman#51]
[Homebrew](https://brew.sh/) based installation would make it much simpler to install talisman on MacOS.

**Comment by svishwanath-tw** [comment]
@prateekbaheti : talisman now uses [go modules](https://github.com/golang/go/wiki/Modules) and therefore defaults to go 1.11 for build and compile.
Maybe the brew build will work now ?

**Comment by dAnjou** [comment]
There is a formula: https://github.com/Homebrew/homebrew-core/blob/master/Formula/talisman.rb. It's out of date though.

**Comment by dineshba** [comment]
Looks the formula is [up to date.](https://github.com/Homebrew/homebrew-core/blob/master/Formula/talisman.rb) We can close this issue @harinee @svishwanath-tw 

May be we can add about brew installation method in readme

**Comment by tinamthomas** [comment]
Closing this and creating an issue to add docs for homebrew installation.
