### ISSUE TITLE
Use a .talismanrc for configuration

### ISSUE THREAD

**Issue by svishwanath-tw** [thoughtworks/talisman#52]
```.talismanrc``` could replace or augment/accompany ```.talismanignore``` (One file seems better, but ... SRP)
Talisman could be used to create and modify the file.
The file could be ```yaml``` or ```json```.

We can club issues #47 by @AikoPath, #39 by @alesti, #33 by @abhsk and  with this issue.

Please see my discussion with @flosell on commits for #38 for some more context/ideas.

**Comment by svishwanath-tw** [comment]
In the interest of avoiding complications, I mostly second what @nossbigg has proposed.
I would however not allow wildcard patterns in talismanrc.
I'd instead what each file individually excluded

What do other folks interested in this feature think ?

**Comment by varac** [comment]
@svishwanath-tw 

> I would however not allow wildcard patterns in talismanrc.

What's the reason for that ? If ppl have a good reason for doing so, why would you like to prevent this ?

**Comment by svishwanath-tw** [comment]
> @svishwanath-tw
> 
> > I would however not allow wildcard patterns in talismanrc.
> 
> What's the reason for that ? If ppl have a good reason for doing so, why would you like to prevent this ?

Wildcards will lead to more lapses in 'security'. It is better to specific about the file/files being ignored.

**Comment by svishwanath-tw** [comment]
@nossbigg I think specific examples will help in reaching a better solution.

Im thinking of static files like images, data files that don't tend to change often and might be picked up by talisman as potential secrets at the time of intro into a repo. These are a one time addition. And you know when you add to talisman ignore, what is happening.

Can you please give examples of files which will change often and will also get detected by talisman as potentially carrying secrets ?

I'm not sure what is being optimized for when you mention efficiency. If it is developer time, I not fully on board. On the one hand there is convenience, on the other it is potential for leaking secrets. Given the nature of this tool, i would err on the side of caution.

**Comment by nossbigg** [comment]
> Can you please give examples of files which will change often and will also get detected by talisman as potentially carrying secrets ?

Eg. files that are generated by build processes are files that naturally change a lot, and any files that may be flagged as false positives will require a lot of manual editing to the talismanrc to ignore the new files. Having matching patterns to match certain build files that are known to have false positives will make it easier for devs to use talisman with less friction.

> I'm not sure what is being optimized for when you mention efficiency. If it is developer time, I not fully on board. On the one hand there is convenience, on the other it is potential for leaking secrets. Given the nature of this tool, i would err on the side of caution.

I'm definitely erring on the side of caution, but my motivation for proposing filename pattern matching is largely motivated by the use case of line-level exclusions across multiple files (as suggested in my [previous comment](https://github.com/thoughtworks/talisman/issues/52#issuecomment-443398406)). Specific to the use case:
1. Without filename pattern matching, users would have to manually add every file with false positives into the .talismanrc, which I imagine would be cumbersome if there are a lot of files
2. Without line-level pattern matching, users would have to exclude a file with false positives entirely, which is not as secure as users may accidentally add secrets in other parts of the file.

Perhaps we can iron out some rough edges before going forward with [this related PR](https://github.com/thoughtworks/talisman/pull/75)?

**Comment by svishwanath-tw** [comment]
> Eg. files that are generated by build processes are files that naturally change a lot, and any files that may be flagged as false positives will require a lot of manual editing to the talismanrc to ignore the new files. Having matching patterns to match certain build files that are known to have false positives will make it easier for devs to use talisman with less friction.

I understand the idea of 'less friction' and also acknowledge that it will go a long way in making talisman a widely adopted/recommended tool in the larger dev community.
I'm not entirely convinced that files produced by build ought to be checked in (are you thinking <package>.min.js ?).

> 1. Without filename pattern matching, users would have to manually add every file with false positives into the .talismanrc, which I imagine would be cumbersome if there are a lot of files

Are we expecting 10's, 100's or 1000's ? And how often would they change once added ?

> 2. Without line-level pattern matching, users would have to exclude a file with false positives entirely, which is not as secure as users may accidentally add secrets in other parts of the file.

I agree that line-level pattern matching will help. False positives + developer frustration is a recipe for disaster.

> Perhaps we can iron out some rough edges before going forward with [this related PR](https://github.com/thoughtworks/talisman/pull/75)?

I'll take a look it ASAP.

**Comment by nossbigg** [comment]
Just double-confirmed that Talisman at present **already** supports folder-level exclusions and file-pattern exclusions for `.talismanignore`. This means that my aforementioned concerns have appeared to be unfounded, I stand corrected 😅

I think we're between a rock and a hard place:
1. drop file pattern matching and lose the flexibility that comes with regexes
2. use file pattern matching and risk accidentally checking in secrets

There's a 3rd option, however - Using checksums in order to mitigate the risks aforementioned in (2). 
I also recognize that going down the path of checksums also means that we need to make it easy for users to add/delete/update checksums and to iron out all the edge cases that come with it (eg. if a file is matched to an ignore rule, but doesn't match its corresponding checksum entry, does talisman fail immediately? what if the file doesn't have an entry in the checksum?).

To me, it seems that our design decisions will have a direct and significant bearing on how `talismanrc` and `checksums` features will look like. I think this deserves a separate conversation on its own for all of us to work the details out together 🖐🏻

**Comment by varac** [comment]
> > Without filename pattern matching, users would have to manually add every file with false positives into the .talismanrc, which I imagine would be cumbersome if there are a lot of files
> Are we expecting 10's, 100's or 1000's ? And how often would they change once added ?

I have an ansible repo with dozens of [git-subrepos](https://github.com/ingydotnet/git-subrepo). Whenever I update a subrepo, talisman will complain about files in these sub-repos, even if I am already using talisman for that sub-repo. I need a way to ignore complete subdir (if this exist it should be documented, see #92), or a way to ignore all `.gitrepo`  files i.e., however they are in a repo.
