### ISSUE TITLE
Ignore content within file option for talismanignore

### ISSUE THREAD

**Issue by aaquibzama-tw** [thoughtworks/talisman#55]
Users should have the ability to ignore specific lines within files which match a certain sensitive content check (format should be: <file_name> <regex_to_ignore>)

**Comment by harinee** [comment]
This should now be extended to .talismanrc as a configuration
Something on the lines of :
customdetection:
- filecontent_pattern: <regex>
- filename_pattern: <regex>

**Comment by mhp-borisbojic** [comment]
Any news on this? We would greatly benefit from the ability to ignore specific strings (for example fixture uuid's or similar). :)

**Comment by harinee** [comment]
This was taken care of in https://github.com/thoughtworks/talisman/issues/183
Please check and see if it suffices. If not, please feel free to reopen
