### ISSUE TITLE
Make Talisman scan at repo level

### ISSUE THREAD

**Issue by aaquibzama-tw** [thoughtworks/talisman#56]
Currently, Talisman only scans the file which are being modified as part of a commit. This change is to ensure that Talisman is capable of scanning all the files at the repo level.

**Comment by harinee** [comment]
Will help if it scans git history

**Comment by mabaritw** [comment]
#83 adds repo level scanner.

**Comment by aaquibzama-tw** [comment]
Issue has been fixed by [v0.4.4](https://github.com/thoughtworks/talisman/tree/v0.4.4)
