### ISSUE TITLE
Detect random strings the could be a password

### ISSUE THREAD

**Issue by varac** [thoughtworks/talisman#62]
Hi, first of all thx for this great tool!

I noticed that talisman fails to detect passwords like this:

```
$ pwgen -1 -ys 36 | tee test-pw
Jz&LBE{b7J.SKn;%w1yJ-gqHQoHe_~g7l+:<
$ git add test-pw
$ git commit -m'test'

 …succeeds
```

I have no clue of talimans algoryhtm to detect secret material, but this case shold be covers (a file only consisting of high entropy random characters).

**Comment by svishwanath-tw** [comment]
Hi @varac, 
talisman does implement shannon entropy based detection, and hex and base64 string detection

Could you suggest any type of detection that could be used to discover and flag strings generated by pwgen as secrets ?

Without enough context around a file, how do we differentiate between actual data and secrets.
We can go by a file name or some metadata before the text.

**Comment by varac** [comment]
Hi @svishwanath-tw, I don't know either cause I didn't look under the hood of talisman. I guessed there might be a way of differentiate passwords. As in a random number of printable characters, which is only a subset of all possible characters like a binary has contains. Hope you understand what you mean.

Of course, filenames containing suspicious strings like  'pw', 'password' etc should raise a red flag as well.

**Comment by harinee** [comment]
Hi @varac 

We have included detection for pattern matching with text containing 'password', 'pw', 'passphrase' etc. (available in https://github.com/thoughtworks/talisman/blob/1f0e05cceb76841ae9c1dd7c3fbac396bfc6ce4d/detector/pattern_detector.go )

Without a logical detail, it is difficult to detect if the given set of chars is random or intended to be such. We need a definitive way of saying what a 'random' printable characters would be. Only then will we be able to convert it to code.

If the pattern matching satisfies your issue, please close this ticket.

**Comment by harinee** [comment]
Closing this, as haven't heard further on the information. Please feel free to reopen with more info and suggestions.
