### ISSUE TITLE
The global unistall script is not able to delete the hooks.

### ISSUE THREAD

**Issue by prachisr** [thoughtworks/talisman#67]
While running the uninstall script, it is not able to delete the hooks created by talisman.

**Comment by svishwanath-tw** [comment]
@prachisr now that the related PR is merged should this be closed ?

**Comment by prachisr** [comment]
@svishwanath-tw We were testing on Windows after this fix. The uninstall script doesn't work on Windows. Though the fix works for Linux/Unix systems.
