### ISSUE TITLE
Scan for `password` etc strings

### ISSUE THREAD

**Issue by varac** [thoughtworks/talisman#70]
Talisman fails to detect this yaml file:

```
room: deploys@conference.jabber.org
username: deploy-bot@jabber.org
password: eytgdtewqy
```

**Comment by svishwanath-tw** [comment]
Hey @varac , please look at https://github.com/thoughtworks/talisman/pull/73 and tell me if this works for you. The code is on master. You could create a build from master and check if that works.

**Comment by varac** [comment]
Thx, works !
