### ISSUE TITLE
Installation fails silently if github rate limits your IP

### ISSUE THREAD

**Issue by tw-pmcfadden** [thoughtworks/talisman#79]
Recently the shared space I work out of has been hitting the Github api request limit. (This happens more frequently in corporations where many share a single external IP) When this happens the script exits with no more information.

I was able to get around this by adding my <username>:<auth token> manually to curl commands in the installation script. Maybe we want to add support for an env variable that will allow people to authenticate?

**Comment by pmcfadden** [comment]
Awesome! Thanks :)
