### ISSUE TITLE
godep failing to resolve all dependencies

### ISSUE THREAD

**Issue by danielsomerfield** [thoughtworks/talisman#8]
When I follow the instructions in the docs, I get the following error:
╰─➤  godep restore
godep: Dep (github.com/Sirupsen/logrus) restored, but was unable to load it with error:
    Package (golang.org/x/sys/unix) not found
godep: Error checking some deps.

Work-around was to first: 
go get golang.org/x/sys/unix

I'm not sure what the right way to solve that really is, so I'll defer to your recommendation rather than make PR.

**Comment by svishwanath-tw** [comment]
Hi @danielsomerfield,
We have moved to go 1.11 and use [go modules](https://github.com/golang/go/wiki/Modules) for dependency management. Im closing this issue now.
