### ISSUE TITLE
recursive "hex encoded" issue with .talismanrc

### ISSUE THREAD

**Issue by prasanna** [thoughtworks/talisman#84]
I upgraded to the latest Talisman. My project has files that contains hex encoded text. Specifically, the project.pbxproj inside the xcodeproj directory for an iOS code base.

I added it to .talismanrc as suggested. I added .talismanrc to git and tried to commit it. Now I get an error saying that .talismanrc has a hex encoded file. If I add it to the .talismanrc file, then it would change it's checksum and it won't work.

The solution is to NOT git add .talismanrc and add it to .gitignore. However, the error message asks you to add .talismanrc to itself.

The error message should ask you to NOT add .talismanrc to git and add it to .gitiignore instead.

**Comment by sriharsha-y** [comment]
Hi @prasanna ,

This has been fixed in PR #86 . Please upgrade talisman binary (https://github.com/thoughtworks/talisman#Upgrading). Kindly close this issue if you think this issue got resolved.

**Comment by harinee** [comment]
Hi @prasanna We are closing this issue after testing it on our end. If you still face any issues, please let us know
