### ISSUE TITLE
Auto-update on Talisman binary

### ISSUE THREAD

**Issue by harinee** [thoughtworks/talisman#96]
When the hook is executed, and if the user is online, there should be a check if the user is using the latest Talisman binary.
If not, there should be an update triggered, which fetches the latest binary and places it in path before further checks happen.
This will ensure that any new detectors etc. are considered.

**Comment by sriharsha-y** [comment]
Hi @harinee ,

This issue has been fixed with #99 PR. Please close this issue if it got resolved.

**Comment by harinee** [comment]
I am waiting for a new release to test the auto-update. So will close this once a new release comes through.

**Comment by harinee** [comment]
Tested. Works!
